# Generated by Django 3.2.4 on 2023-11-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20231105_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtask',
            name='apartement',
        ),
        migrations.RemoveField(
            model_name='addtask',
            name='block',
        ),
        migrations.RemoveField(
            model_name='addtask',
            name='etage',
        ),
        migrations.AddField(
            model_name='stock',
            name='apartement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='block',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='etage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
