# Generated by Django 4.2.4 on 2023-08-31 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0002_stock_purchasing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtask',
            name='user',
            field=models.ForeignKey(default='salem', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
