# Generated by Django 3.2.4 on 2023-11-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20231105_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.FloatField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
