# Generated by Django 4.2.4 on 2023-09-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_addtask_confirmed_alter_addtask_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='purchasing_price',
            field=models.FloatField(default=0, max_length=950),
        ),
    ]
