# Generated by Django 3.2.4 on 2023-11-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stock_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtask',
            name='price_per_item',
        ),
    ]
