# Generated by Django 3.2.4 on 2023-11-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20231111_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addtask',
            options={'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Bien', 'verbose_name_plural': 'Biens'},
        ),
    ]
