# Generated by Django 3.2.4 on 2023-11-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20231111_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtask',
            old_name='date',
            new_name='dateReservation',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='dateReservation',
        ),
        migrations.AlterField(
            model_name='stock',
            name='typeBien',
            field=models.CharField(choices=[('Appartement F2', 'Appartement F2'), ('Appartement F3', 'Appartement F3'), ('Appartement F4', 'Appartement F4'), ('Appartement F5', 'Appartement F5'), ('Service', 'Service'), ('Local', 'Local')], max_length=100),
        ),
    ]
