# Generated by Django 3.2.4 on 2023-11-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20231111_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtask',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='addtask',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='stock',
            name='etat',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Réservé', 'Réservé'), ('Vendu', 'Vendu')], max_length=100),
        ),
    ]
