# Generated by Django 3.2.4 on 2023-11-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20231111_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtask',
            name='user',
        ),
    ]
