# Generated by Django 3.2.4 on 2023-11-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_remove_addtask_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtask',
            name='remaining_parts',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
