# Generated by Django 3.2.4 on 2023-11-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_addtask_remaining_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtask',
            name='NextdatePayement',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
