# Generated by Django 4.2.7 on 2023-11-14 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_addtask_nextdatepayement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='nbrLotsTotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='nomProject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.project'),
        ),
    ]
