# Generated by Django 4.2.7 on 2023-11-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_remove_person_idbiendemande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lieuNaissance',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
