# Generated by Django 4.2.7 on 2023-11-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_alter_person_email_alter_person_lieunaissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lieuNaissance',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
