# Generated by Django 4.2.7 on 2023-11-19 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_alter_person_email_alter_person_lieunaissance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtask',
            old_name='customer',
            new_name='client',
        ),
    ]
