# Generated by Django 4.2.7 on 2023-11-19 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_rename_customer_addtask_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtask',
            old_name='client',
            new_name='customer',
        ),
    ]
