# Generated by Django 4.2.7 on 2023-11-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_rename_client_addtask_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtask',
            name='prixVenteM2',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='prixVenteM2',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
