# Generated by Django 4.2.7 on 2023-11-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_addtask_prixventem2_alter_stock_prixventem2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtask',
            name='total_amount',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
